export const GET_ALL_BOOKING_REQUEST = 'GET_ALL_BOOKING_REQUEST';
export const GET_ALL_BOOKING_SUCCESS = 'GET_ALL_BOOKING_SUCCESS';
export const GET_ALL_BOOKING_FAIL = 'GET_ALL_BOOKING_FAIL';
 
export const REFRESH_BOOKING_REQUEST = 'REFRESH_BOOKING_REQUEST';

export const GET_SINGLE_BOOKING_REQUEST = 'GET_SINGLE_BOOKING_REQUEST';
export const GET_SINGLE_BOOKING_SUCCESS = 'GET_SINGLE_BOOKING_SUCCESS';
export const GET_SINGLE_BOOKING_FAIL = 'GET_SINGLE_BOOKING_FAIL';



export const UPDATE_BOOKING_WORKER_REQUEST = 'UPDATE_BOOKING_WORKER_REQUEST';
export const UPDATE_BOOKING_WORKER_SUCCESS = 'UPDATE_BOOKING_WORKER_SUCCESS';
export const UPDATE_BOOKING_WORKER_FAIL = 'UPDATE_BOOKING_WORKER_FAIL';

export const UPDATE_PAYMENT_STATUS_REQUEST = 'UPDATE_PAYMENT_STATUS_REQUEST';
export const UPDATE_PAYMENT_STATUS_SUCCESS = 'UPDATE_PAYMENT_STATUS_SUCCESS';
export const UPDATE_PAYMENT_STATUS_FAIL = 'UPDATE_PAYMENT_STATUS_FAIL';


export const BOOKING_DELETE_REQUEST = 'BOOKING_DELETE_REQUEST';
export const BOOKING_DELETE_FAIL = 'BOOKING_DELETE_FAIL';
export const BOOKING_DELETE_SUCCESS = 'BOOKING_DELETE_SUCCESS';

export const GET_ALL_NEW_BOOKING_REQUEST = 'GET_ALL_NEW_BOOKING_REQUEST';
export const GET_ALL_NEW_BOOKING_SUCCESS = 'GET_ALL_NEW_BOOKING_SUCCESS';
export const GET_ALL_NEW_BOOKING_FAIL = 'GET_ALL_NEW_BOOKING_FAIL';